### ISSUE TITLE
Build error ubuntu 16.04 CUDA 9

### ISSUE THREAD

**Issue by mrschaeffer2018** [RavenCommunity/kawpowminer#51]
I tried to build in CUDA 9 ubuntu 16.04 on a tesla k80 and i get the error below anyoen can help looks like opencl is the problem i tried to point the path to cuda on the argumetns of cmake but didn't work there is anyway to ignore opencl when building because i'm trying to build only for CUDA, there is a way?
The error and the logs are attached:
-- Build files have been written to: /root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL/Build/OpenCL-Release-prefix/src/OpenCL-Release-buil
[CMakeError.log](https://github.com/RavenCommunity/kawpowminer/files/5976591/CMakeError.log)
[CMakeOutput.log](https://github.com/RavenCommunity/kawpowminer/files/5976592/CMakeOutput.log)

d
[ 75%] Performing build step for 'OpenCL-Release'
Scanning dependencies of target OpenCL
[ 25%] Building C object CMakeFiles/OpenCL.dir/icd_dispatch.c.o
[ 50%] Building C object CMakeFiles/OpenCL.dir/icd.c.o
[ 75%] Building C object CMakeFiles/OpenCL.dir/icd_linux.c.o
In file included from /root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL/Source/icd.c:39:0:
/root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL/Source/icd_dispatch.h:66:19: fatal error: GL/gl.h: No such file or directory
compilation terminated.
CMakeFiles/OpenCL.dir/build.make:62: recipe for target 'CMakeFiles/OpenCL.dir/icd.c.o' failed
make[5]: *** [CMakeFiles/OpenCL.dir/icd.c.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL/Source/icd_dispatch.c:38:0:
/root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL/Source/icd_dispatch.h:66:19: fatal error: GL/gl.h: No such file or directory
compilation terminated.
CMakeFiles/OpenCL.dir/build.make:86: recipe for target 'CMakeFiles/OpenCL.dir/icd_dispatch.c.o' failed
make[5]: *** [CMakeFiles/OpenCL.dir/icd_dispatch.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OpenCL.dir/all' failed
make[4]: *** [CMakeFiles/OpenCL.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/OpenCL-Release.dir/build.make:114: recipe for target 'OpenCL-Release-prefix/src/OpenCL-Release-stamp/OpenCL-Release-build' failed
make[2]: *** [OpenCL-Release-prefix/src/OpenCL-Release-stamp/OpenCL-Release-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OpenCL-Release.dir/all' failed
make[1]: *** [CMakeFiles/OpenCL-Release.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /root/.hunter/_Base/e14bc15/b4bd535/e6a953b/Build/OpenCL
[hunter ** FATAL ERROR **] [Directory:/root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/projects/OpenCL]

------------------------------ ERROR -----------------------------
    https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/modules/hunter_download.cmake:617 (hunter_fatal_error)
  /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/projects/OpenCL/hunter.cmake:43 (hunter_download)
  /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  libethash-cl/CMakeLists.txt:26 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/kawpowminer/build/CMakeFiles/CMakeOutput.log".
See also "/kawpowminer/build/CMakeFiles/CMakeError.log".
